NUMPY CRASH COURSE

In [2]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

In [6]:
import sys

In [8]:
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

Creating List

In [11]:
mylist=[0,1,2,3,4,5]


In [15]:
type(mylist)

list

In [17]:
arr=np.array(mylist)

In [24]:
type(arr)

numpy.ndarray

In [26]:
arr

array([0, 1, 2, 3, 4, 5])

In [32]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

12-Mar-2025

In [56]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(3.0)

array([0., 1., 2.])

In [64]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [70]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [72]:
np.arange(20,10)

array([], dtype=int32)

In [78]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [82]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [84]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [90]:
np.zeros(3)

array([0., 0., 0.])

In [92]:
np.zeros(10) #parameter tunning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [174]:
np.zeros(10, dtype=int) #hyper parameter tunning

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [102]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [104]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [119]:
np.zeros((5,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [121]:
np.ones(3)

array([1., 1., 1.])

In [123]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [138]:
np.ones((5,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [144]:
random.rand(3,2)

NameError: name 'random' is not defined

In [164]:
np.random.rand(3,2)

array([[0.85279146, 0.12637833],
       [0.84151578, 0.67456428],
       [0.89244231, 0.46795685]])

In [166]:
np.random.rand(3,5)

array([[0.68239894, 0.87577995, 0.60397756, 0.14121132, 0.2632935 ],
       [0.92030451, 0.14879092, 0.39308826, 0.50776319, 0.25522969],
       [0.90782919, 0.82122201, 0.5559576 , 0.59737097, 0.28566152]])

In [172]:
np.random.randint(2,5,dtype=int)

4