# 1. Array Creation Functions

In [1]:
import numpy as np

In [3]:
# Create an array from a list
a = np.array([1, 2, 3])
print("Array a:", a)

Array a: [1 2 3]


In [25]:
# Create an array with evenly spaced values
b = np.arange(0, 10, 3)  # Values from 0 to 10 with step 2
print("Array b:", b)

Array b: [0 3 6 9]


In [29]:
# Create an array with linearly spaced values
c = np.linspace(0, 1, 4)  # 4 values evenly spaced between 0 and 1
c1=np.linspace(0,2,5)#5 values evenly spaced between 0 and 2
print("Array c1:",c1)
print("Array c:", c)

Array c1: [0.  0.5 1.  1.5 2. ]
Array c: [0.         0.33333333 0.66666667 1.        ]


In [13]:
# Create an array filled with zeros
d = np.zeros((2, 3))  # 2x3 array of zeros
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# Create an array filled with ones
e = np.ones((3, 2))  # 3x2 array of ones
print("Array e:\n", e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
# Create an identity matrix
f = np.eye(5)  # 5x5 identity matrix
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 2. Array Manipulation Functions

In [23]:
# Reshape an array
a1 = np.array([1, 2, 3,4,5,6])
reshaped1 = np.reshape(a1, (2, 3))  # Reshape to 2x3
reshaped2 = np.reshape(a1, (3, 2))  # Reshape to 2x3
print("Reshaped array: \n", reshaped1)
print("Reshaped array: \n", reshaped2)

Reshaped array: 
 [[1 2 3]
 [4 5 6]]
Reshaped array: 
 [[1 2]
 [3 4]
 [5 6]]


In [33]:
# Flatten an array
f1 = np.array([[1, 2], [3, 4], [3,6]])
flattened = np.ravel(f1)  # Flatten to 1D array
print("Flattened array:", flattened)

Flattened array: [1 2 3 4 3 6]


In [41]:
# Transpose an array
e1 = np.array([[1, 2, 5], [3, 4,6]])
transposed = np.transpose(e1)  # Transpose the array
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]
 [5 6]]


In [45]:
# Stack arrays vertically
a2 = np.array([1, 2, 3])
b2 = np.array([3, 4, 5])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2 3]
 [3 4 5]]


# 3. Mathematical Functions

In [49]:
# Add two arrays
g = np.array([1, 2, 3, 4])
added = np.add(g, 4)  # Add 4to each element
print("Added 4 to g:", added)

Added 4 to g: [5 6 7 8]


In [51]:
# Square each element
squared = np.power(g, 2)  # Square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [72]:
cubed = np.power(g, 3)  # cube each element
print("cubes g:", cubed)

cubes g: [ 1  8 27 64]


In [24]:
# Square root of each element
sqrt_val = np.sqrt(g)  # Square root of each element
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [70]:
print(a1)
print(g)

[1 2 3 4 5 6]
[1 2 3 4]


In [74]:
# Dot product of two arrays
a1=np.array([2,2,2])
a2 = np.array([1, 2, 3])
dot_product = np.dot(a2, a1)  # Dot product of a1 and a2
print("Dot product of a and g:", dot_product)

Dot product of a and g: 12


In [82]:
print(a)
print(a1)

[1 2 3]
[2 2 2]


In [90]:
b1=np.array([[1,2],[2,3]])
b2=np.array([[1,2],[2,3]])
print(id(b1))
print(id(b2))
tow_dim_prod= np.dot(b1,b2)
print("Dot product: ", tow_dim_prod)

2231126828368
2231093796880
Dot product:  [[ 5  8]
 [ 8 13]]


In [92]:
a3 = np.array([3, 2, 3])
dot_product = np.dot(a1, a3)  # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 16


# 4. Statistical Functions

In [31]:
s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [32]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [33]:
# Minimum element of an array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [34]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


# 5. Linear Algebra Functions

In [94]:
# Create a matrix
matrix = np.array([[1, 2], [3, 4]])

In [96]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:", determinant)

Determinant of matrix: -2.0000000000000004


In [98]:
# Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# 6. Random Sampling Functions

In [104]:
# Generate random values between 0 and 1
random_vals = np.random.rand(5)  # Array of 5 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.43758721 0.891773   0.96366276 0.38344152 0.79172504]


In [110]:
# Set seed for reproducibility
np.random.seed(1)

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [123]:
# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [2 4 7 7 9]


In [127]:
# Set seed for reproducibility
np.random.seed(1)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 8 9 5 0]


# 7. Boolean & Logical Functions

In [129]:
# Check if all elements are True
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [133]:
# Check if all elements are True
logical_test = np.array([True, True, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: True


In [135]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [138]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: False


# 8. Set Operations

In [146]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 5, 7, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3]


In [148]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6 7]


# 9. Array Attribute Functions

In [154]:
# Array attributes
a = np.array([1, 2, 3])
b= np.array([[1,2,3],[1,2,3]])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

shape = b.shape  # Shape of the array
size = b.size    # Number of elements
dimensions = b.ndim  # Number of dimensions
dtype = b.dtype   # Data type of the array

print("Shape of b:", shape)
print("Size of b:", size)
print("Number of dimensions of b:", dimensions)
print("Data type of b:", dtype)



Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int32
Shape of b: (2, 3)
Size of b: 6
Number of dimensions of b: 2
Data type of b: int32


# 10. Other Functions

In [156]:
# Create a copy of an array
a = np.array([1, 2, 3])
b=a;
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [89]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 12


In [158]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
assigned=np.shares_memory(a,b)
print("Do a and copied_array share memory?", shared)
print("Do a and assigned_array share memory?", assigned)

Do a and copied_array share memory? False
Do a and assigned_array share memory? True
